// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolOlympiads.InfrastructureServices.Gateways.Database;

namespace SchoolOlympiads.WebService.Migrations
{
    [DbContext(typeof(OlympiadContext))]
    [Migration("20200518152728_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("SchoolOlympiads.DomainObjects.Olympiad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Olympiads");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Class = "7 - 11",
                            Name = "Всероссийская олимпиада по технологии",
                            Subject = "Технология ",
                            Type = "Всероссийская олимпиада",
                            Year = 2015
                        },
                        new
                        {
                            Id = 2L,
                            Class = "6 - 7",
                            Name = "Математический праздник",
                            Subject = "Математика",
                            Type = "Московская олимпиада",
                            Year = 2016
                        },
                        new
                        {
                            Id = 3L,
                            Class = "5 - 11",
                            Name = "Московская астрономическая олимпиада",
                            Subject = "Астрономия",
                            Type = "Московская олимпиада",
                            Year = 2016
                        },
                        new
                        {
                            Id = 4L,
                            Class = "5 - 11",
                            Name = "Московская математическая олимпиада",
                            Subject = "Математика",
                            Type = "Московская олимпиада",
                            Year = 2016
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
